import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import _ from "lodash";
import { Inter } from "@next/font/google";
import { useAccount, useNetwork } from "wagmi";
import { Box } from "@mui/material";
import mainPic from "../public/icons8-main-pic.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { address, isConnected } = useAccount();
  const { chain } = useNetwork();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!_.isNil(chain) && (
        <Box sx={{ maxWidth: "70rem", mx: "auto", textAlign: "center" }}>
          <Box>Welcome to you dope portfolio!😎</Box>

          <Box>
            Go to <Link href="/dashboard">Dashboard</Link> to check it out!
          </Box>

          <Box
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Image src={mainPic} alt="main pic" width={125} height={125} />
          </Box>
        </Box>
      )}
    </>
  );
}
